name: golang-publication
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs: 
  test:
    runs-on: ubuntu-latest
    container: golang:1.24.1
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: GOOS=linux GOARCH=amd64 go test .

      - name: Vet
        run: |
          go vet ./.
  deploy: 
    name: push to dockerHub if tags exist
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DocHub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with: 
          images: dizao9/sprint13final
      
      - name: Build and push Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}